--- 
  components: 
    schemas: 
      AgriFarm: 
        $ref: "https://raw.githubusercontent.com/smart-data-models/dataModel.Agrifood/master/AgriFarm/model.yaml#/AgriFarm"
  info: 
    description: |
      This entity contains a harmonised description of a generic app made for the
      Agrifood domain. This entity is primarily associated with the agricultural
      vertical and related IoT applications.
    title: AgriFarm
    version: "1.0.0"
  openapi: "3.0.0"
  
  # These paths are merely representative.
  paths: 
    /ngsi-ld/v1/entities: 
      get: 
        description: "Retrieve a set of entities which matches a specific query from an NGSI-LD system"
        parameters: 
          - 
            in: query
            name: type
            required: true
            schema: 
              enum: 
                - AgriFarm
              type: string
        responses: 
          ? "200"
          : 
            content: 
              application/ld+json: 
                examples: 
                  keyvalues: 
                    summary: "Key-Values Pairs"
                    value: 
                      - 
                        $ref: "https://raw.githubusercontent.com/smart-data-models/dataModel.Agrifood/master/AgriFarm/examples/example-normalized.json"
                  normalized: 
                    summary: "Normalized NGSI-LD"
                    value: 
                      - 
                        $ref: "https://raw.githubusercontent.com/smart-data-models/dataModel.Agrifood/master/AgriFarm/examples/example-normalized-ld.jsonld"
            description: OK
        tags: 
          - ngsi-ld
  tags: 
    - 
  
      description: "NGSI-LD Linked-data Format"
      name: ngsi-ld
